### ISSUE TITLE
In the Dataset "Terrestrial Water Storage Anomalies" on several dates no layer is shown on the map

### ISSUE THREAD

**Issue by Catalina-Moller** [NASA-IMPACT/veda-data-pipelines#210]
**Description:**
In the Dataset "Terrestrial Water Storage Anomalies" no layer is shown on the map between Jan 2nd, 2001 to Feb 1st, 2002 and no layer is shown on the map between Dec 2nd, 2021 to Jan 1st, 2022.

**Evidence:** 
![image](https://user-images.githubusercontent.com/111894012/197605759-28abe2d2-6767-49d3-8109-f566c0c71191.png)

Url:
https://www.earthdata.nasa.gov/dashboard/eis/datasets/tws-anomaly/explore?datetime=2001-0102T00%3A00%3A00.000Z&position=0%7C27.3089%7C1.12

### **Acceptance Criteria:**
The user should see a layer covering the map of the "Terrestrial Water Storage Anomalies" Dataset on each available date.

**Comment by anayeaye** [comment]
#192 is the cause of this issue so I am linking

**Comment by anayeaye** [comment]
@Catalina-Moller the cause of this issue was that many of the underlying COG files were invalid (researched in #192 and #228). The invalid COGs have been deleted and the associated records have been removed from the database. Can you do a final QA that this dataset is now working as expected in the dashboard?

**Comment by Catalina-Moller** [comment]
The dataset behaves as expected!!
Attached here is some [evidence ](https://www.screencast.com/t/dTlSA6mzvva) of its performance.
