### ISSUE TITLE
Global Terrestrial Water Storage (TWS) anomalies missing or breaking before September 2002

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-data-pipelines#223]
When exploring TWS anomaly data, the browser first starts at the apparently earliest date in the series, 2001-01-02 https://www.earthdata.nasa.gov/dashboard/eis/datasets/tws-anomaly/explore?datetime=2001-01-02T00%3A00%3A00.000Z&position=-113.3999%7C40.4354%7C6.64. 

However, that map is empty - no data shown anywhere globally (turns out all map tiles returned are transparent):

![image](https://user-images.githubusercontent.com/3404817/200808234-144905e9-e69c-4da4-9136-bacea0b45978.png)

This issue continues through 2002-09-01, where data starts showing up. https://www.earthdata.nasa.gov/dashboard/eis/datasets/tws-anomaly/explore?datetime=2002-09-01T00%3A00%3A00.000Z&position=-105.9699%7C40.6867%7C4.84

![image](https://user-images.githubusercontent.com/3404817/200808822-367b5eec-e3f0-4da8-90bf-06e4d1da06df.png)

In the period between 2001-01-02 to 2002-09-01, data coverage is very patchy - many dates are missing:
![image](https://user-images.githubusercontent.com/3404817/200808433-fbebf20e-e268-441a-acf8-fda9a9ff51d4.png)

**Comment by anayeaye** [comment]
We really need to work #192

**Comment by dfelikson** [comment]
From Wanshu Nie:

Hi Denis and Jonas,
 
I’m cc’ing my colleague Shahryar since he has put together this dataset onto the dashboard and know more about the details. But he is now at leave and may not be able to access email.
 
The original dataset that I shared with Shahryar should start from 2002.8.1 and end by 2021.12.1. I’m not sure why some of the dates are not accessible in between 2002.8.1 and 2002.9.1. Are you working on the data visualization for “Water Cycle and Coastal Risk discovery”? If that is the purpose, I would suggest using data from 2003.1.1 onwards.
 
Best,
Wanshu

**Comment by dfelikson** [comment]
@j08lue - based on Wanshu's comment, if we limit the dataset to being displayed over 2003.1.1 - 2021.12.2, would that fix this issue?

**Comment by j08lue** [comment]
> if we limit the dataset to being displayed over 2003.1.1 - 2021.12.2, would that fix this issue?

Yes. If that is fine, we can actually skip #192 (which is a duplicate of this ticket). Would be great to clean up `veda-data-store-staging` for any TWS assets not linked anymore then. I'll create a new ticket to rule them all...
