### ISSUE TITLE
How to handle changes from other projects (such as MAAP)

### ISSUE THREAD

**Issue by abarciauskas-bgse** [NASA-IMPACT/veda-data-pipelines#262]
## Description
I have made some changes that I need to use VEDA data pipelines for MAAP, viewable here: https://github.com/NASA-IMPACT/veda-data-pipelines/compare/main...ab/for-maap2?expand=1

Changes fall into the following buckets:
1. naming changes - these seem the least controversial
2. merging in changes from @moradology and similar changes I made to cmr-discovery to support `start_after` and triggering a next discovery - these seem to be useful to both projects but in the midst of a move to airflow, may no longer be the approach for scaling for VEDA. I don't anticipate adopting airflow for MAAP _yet_ but could do so in the future.
3. changes in build-stac/utils/stac.py (and a bit in cmr-discovery) to address mapping CMR records into STAC records. I think this needs more thought and perhaps to be built into a library. So I think I would pull them out of any changes I would request to be merged.

## Question

Should (1) and (2) be merged into veda-data-pipelines OR since there is an imminent migration to workflow, should I, for now, fork this project into the MAAP-Project organization

### Acceptance Criteria:

- [ ] Decision about how to move forward with changes in ab/for-maap2

**Comment by anayeaye** [comment]
@abarciauskas-bgse sorry for the huge delay in response here but I wanted to acknowledge this issue! I think at a minimum we need to incorporate some of the naming and CMR changes into the pipelines after the architecture changes settle. It seems like a fork makes sense while the pipelines are potentially changing but we need to capture the essential changes you had to implement for MAAP so that we don't have to re-learn/re-implement the same things the first time we try and add similar data to VEDA.

**Comment by abarciauskas-bgse** [comment]
Thanks @anayeaye 

In that case I will create a fork with my changes and wait until the architecture changes settle.
