### ISSUE TITLE
Created list of datasets in the COVID dashboard that are missing in the VEDA data store

### ISSUE THREAD

**Issue by slesaad** [NASA-IMPACT/veda-data-pipelines#275]

**Comment by smohiudd** [comment]
Based on this [api](https://8ib71h0627.execute-api.us-east-1.amazonaws.com/v1/datasets), the following datasets are included in the Covid dashboard:
```
['agriculture',
 'co2-diff',
 'co2',
 'detections-contrail',
 'detections-plane',
 'detections-ship',
 'detections-vehicles',
 'fb-population-density',
 'gibs-population',
 'nightlights-hd',
 'nightlights-viirs',
 'no2-diff',
 'no2',
 'recovery',
 'slowdown',
 'togo-ag',
 'water-chlorophyll',
 'water-pzd',
 'water-spm']
```
It looks like `['agriculture', 'co2-diff', 'co2', 'fb-population-density','no2-diff', 'no2', 'nightlights-hd' ]` are currently included in the VEDA dashboard however some of the datasets are not complete, i.e. do not include the most recent data as shown in the COVID dashboard

**Comment by smohiudd** [comment]
Note that the `detections-*` datasets are geojson and not rasters...

**Comment by smohiudd** [comment]
Here is a [spreadsheet](https://docs.google.com/spreadsheets/d/1EwMmxa36hP9n6rv-rYNHplIAChCt69528GKH3Yi2dPQ/edit?usp=sharing) that lists the COVID dashboard datasets and their buckets.

**Comment by moradology** [comment]
Some of these datasets work well with a little massaging of filenames to match our conventions around datetime but others ([rpm](https://s3.console.aws.amazon.com/s3/buckets/covid-eo-data?region=us-east-1&prefix=rpm/), for instance) aren't so obvious. Is there a reference that I could consult for this data?

**Comment by moradology** [comment]
I believe this issue can be marked as done. I compared counts for all datasets that we had (there appear to be some datasets that we *could* bring over from this list but have not). Co2 datasets and FB population both appear to be caught up; GEOGLAM appears to actually be *ahead* of the covid-eo-data bucket's contents. The only data that appeared to be behind that found in the covid-eo-data bucket were the no2 datasets, which can be found [here](https://s3.console.aws.amazon.com/s3/buckets/climatedashboard-data?region=us-east-1&prefix=OMNO2d_HRM/&showversions=false) and [here](https://s3.console.aws.amazon.com/s3/buckets/climatedashboard-data?region=us-east-1&prefix=OMNO2d_HRMDifference/&showversions=false).

As an aside it seems as though we could simplify things if the `cogification` and `data-transfer` tasks were simply done separately from discovery and ingest of stac records because this seems to be a completely separate concern and the workflow now is to run a throw-away `'upload': true` ingest and then swap out bucket/prefix arguments for subsequent `upload: false` ingests. Wouldn't it make sense to have a single, well-defined process for renaming, cogifying (if necessary), and moving tifs to the bucket where discovery is expected?

**Comment by j08lue** [comment]
Perhaps just update the table above and then we can close this issue - it was only about listing the datasets, anyways?
