### ISSUE TITLE
Design Spike: HLS ingest

### ISSUE THREAD

**Issue by slesaad** [NASA-IMPACT/veda-data-pipelines#276]
## PI Objective
[Complete / gap-fill partial datasets and metadata, to become a reliable source for selected ARCO datasets in user](https://github.com/NASA-IMPACT/veda-architecture/issues/161)

## Description
HLS L30 and S30.
- HLS STAC records already exist (in multiple locations). Confirm the best one to use. ([CMR STAC records](https://cmr.earthdata.nasa.gov/stac/LPCLOUD/collections/HLSS30.v2.0/items)
- Estimate the size of the backfill
- Design how to ingest it via veda-data-pipelines
- Explore data provider trigger for automatic ingests (Stretch)

### Acceptance Criteria:

- [ ] https://github.com/NASA-IMPACT/veda-architecture/issues/212

**Comment by moradology** [comment]
1. Do we happen to know of a list (comprehensive or not) of alternatives? it appears that the list here prematurely ended after CMR)
2. I'm seeing 6151451 records in the CMR HLS collection
3. Assuming we can keep the data where it is (rather than copying over and cogifying the millions of assets), it seems like it might be acceptable to copy+modify records from the source we choose in 1
4. TBD

**Comment by anayeaye** [comment]
@moradology I can't speak to all of these right off but, 

1. I _think_ there is probably a way to make a https://cmr.earthdata.nasa.gov/search/ (not CMR-stac) search to identify all HLS data in s3 as well as the S3 object URLs (and possibly STAC metadata objects). I don't know that we need to have a CMR discovery based design but I do think there might be some useful information for us in CMR for the research part of this task.

3. Yes we want to keep the data in place, the existing STAC metadata should just need the non-DOI/data provenance links stripped out and the asset urls modified for s3 (the metadata may be stored in s3 inline, too, if we can find it). I think the pass through metadata publication work from the landsat ingest could definitely be useful to this design task.

4. While it is listed as a stretch goal, I actually think the easiest way to design the HLS ingest system might be to find a way to subscribe to SNS notifications from the HLS processing pipelines for forward ingests and then design a CMR/stac search or S3 based search for back filling second. We should try to sync with @sharkinsspatial and @freitagb about what has been learned from the HLS work.

**Comment by j08lue** [comment]
Great you are moving on this, @moradology and @anayeaye.

So this ticket is only asking for a design, not the actual work. But would it be an idea to actually copy some subset of HLS data into our catalog, as a prototype?

I guess once we have the metadata transformation to nice STAC records for our catalog in place, one could, like you suggested, @anayeaye, actually work on a prototype for an ingestion trigger.

A great outcome for this ticket would be a consolidated write-up (here or in [this folder](https://drive.google.com/drive/folders/1E_bUjP8DoIhVBugnnsqoztuCIjbfgfH9)) of the volume and any challenges we see, plus a little prototype in the form of either some bulk ingest of part of the archive (say the last year global coverage or CONUS) or a trigger that ingests newly published HLS from here on. Only if feasible, though - just design docs are fine, too.

**Comment by sharkinsspatial** [comment]
As a bit of background, I undertook some related work in order to enable HLS data integration with FIRMS using a `titiler-pgstac` but this was primarily focused on ingesting forward processed data as it was produced in order to support near real time wildfire visualization.  I can detail a few potential options.  The main questions are how we 
1. Ingest STAC items for the existing archive of HLS data.
2. Continuously ingest STAC items for new HLS data as it is produced.

With respect to # 1 there are two steps to consider,  historical granule discovery and  choosing the existing inline STAC item or regeneration.  

Though I was focused on forward processing, I did include some functionality for discovering historical data in my research.  A rudimentary CMR search function is available at https://github.com/NASA-IMPACT/cmr-pgstac-loader/blob/main/lambdas/cmr_query/handler.py.  You'd need to set up a proper paging/chunking state management system to manage moving through these pages using some type of chunking strategy to reduce your query response size but that should be fairly straightforward (@anayeaye I can point you to examples of this in a private DevSeed repo).

The next question is whether you want to use the existing inline HLS STAC item or generate a new one.  The inline STAC items are fairly [comprehensive](https://github.com/NASA-IMPACT/hls-cmr_stac) but only include `https` `assets`.  I was [transforming](https://github.com/NASA-IMPACT/cmr-pgstac-loader/blob/main/lambdas/build_ndjson/handler.py#L23-L35) `assets` to `s3` prior to ingestion for use with our tiler.  There is a known [issue](https://github.com/NASA-IMPACT/hls-cmr_stac/releases/tag/v1.7) with the inline STAC items in the archive produced prior to May 2022 that has not been retroactively fixed so you'd also need to update these EPSG codes for that time period.  The other option would be to use newly released [HLS stactools package](https://github.com/stactools-packages/hls) to remote read granules and generate new STAC items with even more detailed extensions.  We will eventually adopt this package for inline item generation but we're momentarily restricted by the Python version running on our container.

With respect to #2 the biggest issue is that the DAACs and Cumulus do not current provide a standard notification publication system for new data.  The SNS topic we use with https://github.com/NASA-IMPACT/cmr-pgstac-loader is an internal one for sending new granule notifications to Cumulus and should not be relied on by external production systems (its usage for the FIRMS tiler was purely experimental).  Additionally, this suffers from the issue that when we publish a new HLS granule there is still a latency period (or potential for failure) for its Cumulus ingestion and eventual publication to the DAAC's S3 bucket which can result in "orphan" STAC items who's assets don't actually exist.

Until the DAACs can provide a consistent publication topic (which we've requested numerous times) you'll be reduced to periodically running CMR queries based on publication date in order to discover newly created data.  This also suffers from potential query / publication race and offset conditions due to CMR latency issues and can result in some reconciliation headaches.

We've also requested that the DAACs consider the usage of bucket inventories to support these large scale archival data interaction efforts.  @anayeaye This is the approach we take internally for work with our other partners.  We ingest the inventory into Athena and then use a customized query function to step through the inventory in reasonable chunk sizes and queue the ingestions.  We've raised this a few times with various DAAC representatives but haven't seen much movement.

**Comment by moradology** [comment]
This is my first dance with CMR and it is... not the most user friendly system for those that are new to it but after some trial and error I think I'm getting close to a very simple process that ought to be sufficient for bulk loading. Pagination alone doesn't appear to be sufficient, as the page depth necessary (nearly 7 million records) is in excess of what is supported (at most 1 million records). To get around this we can use the `CMR-Search-After` header, which has no issue with paging depth.

Unclear on the status of `stactools-hls` as it appears not to live on pypi:
`pip install stactools-hls` fails and https://pypi.org/project/stactools-hls/ appears to 404.

Anyway, here's an attempt at charting out a course to the full, bulk load of CMR data (task 1) for `HSLS30` and `HSLL30` with some possible strategies implicitly available for ingesting only later records (task 2) if a `search_after` argument is supplied:
```python
#!/usr/bin/env python3
import json
import os

import requests
import retry

GRANULE_SEARCH_URL = f"https://cmr.earthdata.nasa.gov/search/granules.json"

def search_after_to_string(search_after):
    if search_after == None:
        return "root"
    else:
        return "_".join(search_after.split(","))

def string_to_search_after(string):
    if string == "root":
        return None
    else:
        return ",".join(string.split("_"))

@retry.retry(requests.exceptions.RequestException, tries=5, delay=2, backoff=2)
def get_item(url):
    response = requests.get(url)
    item = response.json()
    item["properties"]["proj:epsg"] = 32635
    return item


@retry.retry(requests.exceptions.RequestException, tries=5, delay=2, backoff=2)
def bulk_load_ndjson(short_name, page_size=2000, search_after=None, max_pages=None):
    """This function will attempt to load all stac items from CMR for a given short name.
    example search_after: ["lpcloud",1498759811680,2264210565]
    """
    if max_pages and search_after:
        print(f"Ingesting {short_name} starting after {search_after} for {max_pages} pages")
    elif max_pages:
        print(f"Ingesting {short_name} for {max_pages} pages")
    elif search_after:
        print(f"Ingesting {short_name} starting after {search_after}")
    else:
        print(f"Ingesting *all* of {short_name} (this may take a while...)")

    params = {
        'page_size': page_size,
        'short_name': short_name
    }
    page = 1

    output_directory = "ndjson_output"
    if not os.path.exists(output_directory):
        os.makedirs(output_directory)
    while True:
        if search_after:
            response = requests.get(GRANULE_SEARCH_URL, params=params, headers={'CMR-Search-After': search_after})
        else:
            response = requests.get(GRANULE_SEARCH_URL, params=params)
        data = response.json()
        with open(f"{output_directory}/{short_name}_{search_after_to_string(search_after)}.ndjson", "w") as f:
            for entry in data['feed']['entry']:
                for link in entry['links']:
                    if 'stac' in link.get('title', ""):
                        stac_url = link['href']
                        stac_item = get_item(stac_url)
                        json.dump(stac_item, f)
                        f.write("\n")

        # for debugging
        if page == max_pages:
            print(f"Max pages ({max_pages}) reached for {short_name}")
            break

        if response.headers['CMR-Search-After']:
            search_after = response.headers['CMR-Search-After']
            page = page + 1
        else:
            print(f"No more pages for {short_name}")
            break


if __name__ == "__main__":
    bulk_load_ndjson("HLSS30", page_size=2, max_pages=5)
    bulk_load_ndjson("HLSL30", page_size=2, max_pages=5)
```
