### ISSUE TITLE
Add COVID Nightlights VIIRS Dataset

### ISSUE THREAD

**Issue by smohiudd** [NASA-IMPACT/veda-data-pipelines#296]
Dataset is stored in: `s3://covid-eo-data/viirs/source_data/COVID19_Dashboard_BMHD/`

- [ ] Verify that files are valid COGs (e.g. with [`rio cogeo validate`](https://cogeotiff.github.io/rio-cogeo/Is_it_a_COG/#3-cog-validation))
- [ ] Gather STAC collection metadata

  - id:
  - title:
  - description:
  - license:
  - temporal interval:
  - whether it is periodic on the dashboard (periodic = regular time series of layers without gaps):
  - the dashboard time density:

- [ ] Review and follow https://github.com/NASA-IMPACT/cloud-optimized-data-pipelines/blob/main/OPERATING.md
- [ ] Create mdx in `veda-config `and open PR for publishing those datasets to the Staging API
- [ ] Once approved, merge and close.

**Comment by moradology** [comment]
This is VIIRS data configured for a covid dashboard that spotlights specific locations. What collection-level information do we want to provide?

**Comment by anayeaye** [comment]
In a review of remaining covid-19 dashboard data to transfer to VEDA ([documented here](https://docs.google.com/document/d/1xiBf9Awo8DShrRJhMZcfhunchEynUTA52xHzYZQZ0HE/edit#)), we decided not to transfer the COVID19 VIIRS data because the corrected/improved single band nightlights HD data were used in VEDA's air quality discovery instead of this dataset and those data have worked for all cases. The coverage of the HD data is very similar to the raw VIIRS and because there is no provenance data for those datasets, they do not add value above the nightlights-hd-monthly collection we already have in VEDA.
